# Etapa 1: Build
FROM oven/bun:alpine as builder

WORKDIR /app

COPY bun.lockb package.json ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

# Etapa 2: Producción 
FROM oven/bun:alpine

WORKDIR /app

COPY --from=builder /app .

RUN bun install --frozen-lockfile --production

EXPOSE 3000

CMD ["bun", "run", "prod"]
